### ISSUE TITLE
Recent LLM/2024-May onward on RK3588

### ISSUE THREAD

**Issue by briliantnugraha** [Pelochus/ezrknn-llm#13]
Hi @Pelochus , thanks for the great repo to simplify LLM on Rockchip, this is very exciting to me, since we could port LLM on cheap devices.

Btw, I am wondering, have you tried/succeeded in porting newer/recent LLM, like from 2024-May onwards, to RK3588?

I am really curious whether someone has successfully done so or not, as I am only familiar with rknn-toolkit2 (I've been doing CV things on many edge devices, but I've only ported LLMs to those towering PCs / Servers).

Looking forward to your reply.

Best, 
Brilian~

**Comment by Pelochus** [comment]
Hi, thanks for your kind words. The compatible LLMs are listed here:

https://github.com/airockchip/rknn-llm/

So if there is any LLM from May 2024 onwards in that list then I can try to convert whichever you want for you. Some of them (like Phi-3 mini) are already converted

**Comment by Pelochus** [comment]
a. You should use 16GB RAM or even 32GB. 16 should be enough, but if you plan on running more stuff like Docker containers you should use a 32GB RAM. With 4GB RAM, the biggest should be around 3B parameters, depending on the LLM. Gemma 2B doesn't work on 4GB RAM.

b. The NPU usage is very broken. Depending on the LLM it uses 1, 2 or 3 cores. Not much we can do since the library controlling the NPU is closed source.

c. Currently, latest versions of Ubuntu Rockchip from Joshua and Armbian are both OK, perhaps the Joshua one has more Rockchip related updates (like the NPU drivers) 

Aside from that, Llama 3 isn't compatible but Qwen 2 is, so you could try that one.

**Comment by briliantnugraha** [comment]
really appreciate all these info @Pelochus, these info worth a week of testing for me, thanks a lot! 

I will share you the progress when it's ready. For now, I will close the issue, thanks again

Best, Brilian~

**Comment by briliantnugraha** [comment]
hi @Pelochus , just to let you know, thanks to the recommendation, it's runnable and at a fairly quick speed at that!
feel free to check the post that I shared in here, thank you. https://briliantn.com/blog/2024/rockchip-llm/

**Comment by Pelochus** [comment]
Your welcome! Happy to see your results
